#!/usr/bin/env ruby
require 'toml'

services = `networksetup -listnetworkserviceorder`.scan(/\(\d*\).*$/).map do |service|
  service.gsub(/\(\d*\)\s/, '').gsub(/\s/, "\\ ")
end

begin
  proxies = TOML.load_file(File.dirname(__FILE__) + "/config.toml")
rescue
  abort "Failed to load config file"
end

abort "Usage: proxy [on|off|NAME]" if ARGV[0].nil?

way = ARGV[0]
if %w{ on off }.include?(way)
  services.each {|service| `networksetup -setwebproxystate #{service} #{way}`}
else
  current = proxies[way]
  abort "No such proxy configured" if current.nil?
  current["auth"] = current["username"].nil? ? "off" : "on"
  params = %w{ server port auth username password }.map { |attr| current[attr] }.join ' '
  services.each do |service|
    `networksetup -setwebproxy #{service} #{params}`
  end
end
